edition = "2021"
newline_style = "Unix"

max_width = 120

fn_params_layout = "Tall"
fn_call_width = 120

force_multiline_blocks = true
group_imports = "StdExternalCrate"

imports_granularity = "Module"
imports_layout = "HorizontalVertical"
normalize_doc_attributes = true
reorder_impl_items = true
reorder_modules = true

