[workspace]
members = ["crates/*"]
resolver = "2"
# package.rust-version = "1.82.0"

[workspace.metadata]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
exclude = ["target"]

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.dev]
opt-level = 1
codegen-units = 256
incremental = true

[profile.release]
opt-level = 3
codegen-units = 1
debug = "none"
debug-assertions = false
incremental = true

[workspace.dependencies]
# Core dependencies
tokio = { version = "*", features = ["full", "tracing"] }
futures = "*"
async-trait = "*"

# Logging
tracing = "*"
# log = "*"

# Error handling
thiserror = "*"
eyre = "*"

# Database
deadpool-tiberius = { version = "*", features = ["winauth", "chrono"] }
