extend = [
    { path = "./build/common-tasks.toml" },
    { path = "./build/dist-tasks.toml" },
    { path = "./build/watch-tasks.toml", optional = true }
]

## START Full sweeps/aliases
[tasks.b]
run_task = { name = ["format", "build"], parallel = true }

[tasks.br]
run_task = { name = ["format", "build_release"], parallel = true }

[tasks.a]
run_task = { name = [
    "build_workspace",
    "build",
    "test",
    "build_release_workspace",
    "build_release",
    "test_all",
], parallel = true }

[tasks.r]
run_task = { name = ["run"], parallel = false }

[tasks.rr]
run_task = { name = ["run_release"], parallel = false }

[tasks.bw]
run_task = { name = ["build_workspace"], parallel = true }

[tasks.brw]
run_task = { name = ["build_release_workspace"], parallel = true }

[tasks.cl]
run_task = { name = ["clean"], parallel = false }

[tasks.dist]
env.PROFILE = "release"
run_task = { name = ["build_release_dist"], parallel = false }

[tasks.reset]
run_task = { name = ["clean", "a"], parallel = false }
# END Full sweeps/aliases