# If inside a workspace
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_TIME_SUMMARY = true
BIN_NAME = "${CARGO_MAKE_PROJECT_NAME}"
ROOT = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
PROFILE = "${CARGO_MAKE_CARGO_PROFILE}"
#MP = "${CARGO_MAKE_PROFILE}"
#CMP = "${CARGO_MAKE_CARGO_PROFILE}"

# Core bare. min
[tasks.format]
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.build_release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["format"]
# Core bare. min

# Tests
[tasks.test]
command = "cargo"
args = ["test"]

[tasks.test_all]
command = "cargo"
args = ["test", "--all"]

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.run_release]
command = "cargo"
args = ["run", "--release"]

#### Workspace specific(s)

[tasks.build_workspace]
command = "cargo"
args = ["build", "--workspace"]
dependencies = ["format"]

[tasks.build_release_workspace]
command = "cargo"
args = ["build", "--release", "--workspace"]
dependencies = ["format"]

[tasks.test_workspace]
command = "cargo"
args = ["test", "--workspace"]

# DIST STUFF
# -----------------------------------------------------------------------------
[tasks.create_dist]
command = "mkdir"
args = ["-p", "${ROOT}/dist/"]

[tasks.create_showcase_dist]
command = "mkdir"
args = ["-p", "${ROOT}/dist/showcase/"]
dependencies = ["create_dist"]

[tasks.copy_release_to_dist]
command = "cp"
args = ["${ROOT}/target/${PROFILE}/${BIN_NAME}.exe", "dist/"]
dependencies = ["create_dist", "build_release"]

[tasks.copy_readme_to_dist]
command = "cp"
args = ["README.md", "${ROOT}/dist/"]
dependencies = ["create_dist"]

[tasks.build_releae_dist]
dependencies = [
    "build_release_workspace",
    "test_workspace",
    "build",
    "test_all",
    "create_dist",
    "create_showcase_dist",
    "copy_release_to_dist",
    "copy_readme_to_dist",
]
# -----------------------------------------------------------------------------
# DIST STUFF

#[tasks.expand]
#env.MP = "${PROFILE}"
#command = "${ECHO_CMD}"
#args = [
#    "MP: ${MP}",
#]

# -----------------------------------------------------------------------------
[tasks.watch]
command = "cargo"
args = ["watch", "-q", "-c", "-w", "src/", "-x", "run"]

[tasks.watch_release]
command = "cargo"
args = ["watch", "-q", "-c", "-w", "src/", "-x", "run --release"]
# -----------------------------------------------------------------------------

## Full sweeps
[tasks.b]
run_task = { name = ["format", "build"], parallel = true }

[tasks.br]
run_task = { name = ["format", "build_release"], parallel = true }

[tasks.a]
run_task = { name = [
    "build_workspace",
    "build",
    "test",
    "build_release_workspace",
    "build_release",
    "test_all",
], parallel = true }

[tasks.r]
run_task = { name = ["run"], parallel = false }

[tasks.rr]
run_task = { name = ["run_release"], parallel = false }

[tasks.bw]
run_task = { name = ["build_workspace"], parallel = true }

[tasks.brw]
run_task = { name = ["build_release_workspace"], parallel = true }

[tasks.dist]
env.PROFILE = "release"
run_task = { name = ["build_releae_dist"], parallel = true }

[tasks.reset]
run_task = { name = ["clean", "a"], parallel = false }

# , fork = true, cleanup = "clean" 
# , parallel = true, fork = true, cleanup = "clean"

