edition = "2021"
newline_style = "Unix"

max_width = 120

fn_params_layout = "Vertical"
force_multiline_blocks = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
normalize_doc_attributes = true
# overflow_delimited_expr = true
reorder_impl_items = true
# wrap_comments = false
#
# max_width = 120
# use_small_heuristics = "Max"

# fn_call_width = 10
# attr_fn_like_width = 20
# chain_width = 20
# struct_lit_single_line = false
