#!/usr/bin/env python3
"""
update-docs-index.py -- Regenerate docs/index.md from doc frontmatter.

Scans docs/ for .md files with YAML frontmatter, extracts title,
description, keywords, and order, then regenerates the "Docs" section
of docs/index.md between the auto-generated markers.

Files prefixed with _ (e.g. _draft.md) and index.md itself are skipped.

Usage:
    python3 scripts/update-docs-index.py          # run from project root
    python3 scripts/update-docs-index.py --check  # exit 1 if index is stale

Do not modify this script to fit non-standard docs! If a doc lacks
frontmatter or doesn't conform, fix the DOC -- not this script. If the
conformance changes are complex, stop and ask the user.

Requires: pyyaml (pip install pyyaml)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Error: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

DOCS_DIR = Path("docs")
INDEX_FILE = DOCS_DIR / "index.md"
MARKER_START = "<!-- AUTO-GENERATED by scripts/update-docs-index.py -- do not edit below this line -->"
MARKER_END = "<!-- AUTO-GENERATED by scripts/update-docs-index.py -- do not edit above this line -->"


def parse_frontmatter(text: str) -> dict | None:
    """Extract YAML frontmatter from markdown text. Returns None if absent."""
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return None

    fm_lines = []
    for line in lines[1:]:
        if line.strip() == "---":
            break
        fm_lines.append(line)
    else:
        # Unclosed frontmatter
        return None

    raw = "".join(fm_lines)
    try:
        return yaml.safe_load(raw) or {}
    except yaml.YAMLError:
        return None


def derive_frontmatter(text: str, filename: str) -> dict:
    """Derive YAML frontmatter from document content when none exists.

    Extracts title from first heading, description from first paragraph,
    keywords from headings/bold text, and order from filename prefix.
    """
    lines = text.splitlines()

    # Title: first # heading
    title = ""
    for line in lines:
        m = re.match(r"^#\s+(.+)", line)
        if m:
            title = m.group(1).strip()
            break

    # Description: first non-empty, non-heading, non-frontmatter line
    desc = ""
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("---"):
            continue
        # Skip code blocks
        if stripped.startswith("```"):
            break
        desc = stripped
        break

    # Keywords: collect words from headings and **bold** text
    kw_candidates: list[str] = []
    for line in lines:
        stripped = line.strip()
        # Headings (skip the title)
        m = re.match(r"^#{1,3}\s+(.+)", stripped)
        if m and m.group(1).strip() != title:
            for word in re.findall(r"[a-zA-Z][a-zA-Z0-9_-]{2,}", m.group(1)):
                kw_candidates.append(word.lower())
        # Bold text
        for bold in re.findall(r"\*\*([^*]+)\*\*", stripped):
            for word in re.findall(r"[a-zA-Z][a-zA-Z0-9_-]{2,}", bold):
                kw_candidates.append(word.lower())

    # Deduplicate, keep order, cap at 8
    seen: dict[str, None] = {}
    for kw in kw_candidates:
        if kw not in seen:
            seen[kw] = None
    keywords = list(seen.keys())[:8]

    # Order: try filename prefix (e.g. "05_architecture.md" -> 5)
    order = 99
    m = re.match(r"^(\d+)_", filename)
    if m:
        order = int(m.group(1))

    return {
        "title": title or filename.replace(".md", "").replace("_", " ").replace("-", " ").title(),
        "description": desc,
        "keywords": keywords,
        "order": order,
    }


def collect_docs(docs_dir: Path) -> tuple[list[dict], list[Path]]:
    """Scan docs/ for .md files. Auto-generates frontmatter when missing.

    Returns (entries, files_needing_review) where files_needing_review
    lists files that got auto-generated frontmatter and should be checked.
    """
    entries = []
    review_needed: list[Path] = []

    for path in sorted(docs_dir.glob("*.md")):
        name = path.name

        # Skip index.md and underscore-prefixed files
        if name == "index.md" or name.startswith("_"):
            continue

        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)

        if fm is None:
            # Auto-generate frontmatter from content
            fm = derive_frontmatter(text, name)
            # Insert frontmatter into the file
            new_text = (
                "---\n"
                f"title: \"{fm['title']}\"\n"
                f"description: \"{fm['description']}\"\n"
                f"keywords: {fm['keywords']}\n"
                f"order: {fm['order']}\n"
                "---\n\n"
                + text
            )
            path.write_text(new_text, encoding="utf-8")
            review_needed.append(path)
            print(f"  [generated] {name} -- frontmatter added, REVIEW recommended", file=sys.stderr)

        title = fm.get("title")
        if not title:
            print(f"Warning: {path} has no title, skipping.", file=sys.stderr)
            continue

        # Normalize description to a single string
        desc = fm.get("description", "")
        if isinstance(desc, list):
            desc = " ".join(str(d) for d in desc)
        desc = str(desc).strip()

        # Normalize keywords to a comma-separated string
        keywords = fm.get("keywords", [])
        if isinstance(keywords, str):
            # Handle inline list like "[k1, k2, k3]"
            keywords = [k.strip() for k in keywords.strip("[]").split(",") if k.strip()]
        elif isinstance(keywords, list):
            keywords = [str(k).strip() for k in keywords if k]
        else:
            keywords = []

        # Order defaults to 99
        order = fm.get("order", 99)
        try:
            order = int(order)
        except (ValueError, TypeError):
            print(f"Warning: {path} has non-numeric order '{order}', defaulting to 99.", file=sys.stderr)
            order = 99

        entries.append({
            "path": path,
            "filename": name,
            "title": str(title).strip(),
            "description": desc,
            "keywords": keywords,
            "order": order,
        })

    # Sort by order, then by filename for stable ordering
    entries.sort(key=lambda e: (e["order"], e["filename"]))
    return entries, review_needed


def build_keywords_union(entries: list[dict]) -> str:
    """Merge all doc keywords into a deduplicated, ordered comma-separated string."""
    seen: dict[str, None] = {}
    for entry in entries:
        for kw in entry["keywords"]:
            key = kw.lower().strip()
            if key and key not in seen:
                seen[key] = None
                # Preserve original casing from first occurrence
                seen[key] = kw
    # Rebuild preserving insertion order
    return ", ".join(v for v in seen.values() if v is not None)


def build_docs_list(entries: list[dict]) -> str:
    """Build the markdown list of doc links from sorted entries."""
    lines = []
    for entry in entries:
        line = f"- [{entry['title']}]({entry['filename']})"
        if entry["description"]:
            line += f" -- {entry['description']}"
        lines.append(line)
    return "\n".join(lines)


def regenerate_index(index_path: Path, entries: list[dict]) -> str:
    """Rewrite docs/index.md, replacing content between markers and keywords."""
    text = index_path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)

    docs_list = build_docs_list(entries)
    keywords = build_keywords_union(entries)

    # Phase 1: Replace Docs section between markers
    output_lines: list[str] = []
    in_marker_section = False

    for line in lines:
        if MARKER_START in line:
            output_lines.append(line)
            output_lines.append("\n")
            output_lines.append(docs_list)
            output_lines.append("\n")
            in_marker_section = True
            continue

        if MARKER_END in line:
            output_lines.append("\n")
            output_lines.append(line)
            in_marker_section = False
            continue

        if not in_marker_section:
            output_lines.append(line)

    # Phase 2: Replace Keywords section
    result_lines: list[str] = []
    in_keywords = False

    for line in output_lines:
        if line.strip() == "## Keywords":
            result_lines.append(line)
            result_lines.append("\n")
            result_lines.append(keywords)
            result_lines.append("\n")
            in_keywords = True
            continue

        if in_keywords:
            # Skip until next heading
            if re.match(r"^#{1,2}[^#]", line):
                in_keywords = False
                result_lines.append("\n")
                result_lines.append(line)
            continue

        result_lines.append(line)

    return "".join(result_lines)


def main() -> int:
    check_only = "--check" in sys.argv

    if not DOCS_DIR.is_dir():
        print(f"Error: {DOCS_DIR}/ directory not found.", file=sys.stderr)
        return 1

    if not INDEX_FILE.is_file():
        print(f"Error: {INDEX_FILE} not found. Create it first with the doc markers.", file=sys.stderr)
        return 1

    entries, review_needed = collect_docs(DOCS_DIR)
    if not entries:
        print(f"No docs with frontmatter found in {DOCS_DIR}/.", file=sys.stderr)
        return 1

    new_content = regenerate_index(INDEX_FILE, entries)

    if check_only:
        current = INDEX_FILE.read_text(encoding="utf-8")
        if current != new_content:
            print("Error: docs/index.md is stale. Run scripts/update-docs-index.py to update.", file=sys.stderr)
            return 1
        print("docs/index.md is up to date.")
        return 0

    INDEX_FILE.write_text(new_content, encoding="utf-8")
    print(f"Regenerated {INDEX_FILE} ({len(entries)} docs indexed).")

    if review_needed:
        print()
        print("NOTE: The following files had frontmatter auto-generated:")
        for p in review_needed:
            print(f"  - {p}")
        print("Review the generated frontmatter (title, description, keywords, order)")
        print("and adjust as needed. Auto-generated keywords may be imprecise.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
