name: "Test"
on:
  push:
    branches:
      - "master"
      - "main"
      - "develop"
      - "dev"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CARGO_TERM_COLOR: "always"
  CARGO_INCREMENTAL: "0"
  RUST_BACKTRACE: "1"
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  PROJECT_NAME: "rust_template"

jobs:
  test:
    name: "Test - ${{ matrix.target }}"
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
    runs-on: "${{ matrix.os }}"
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - name: "Checkout sources"
        uses: "actions/checkout@v7"

      - name: "Setup Rust"
        uses: "./.github/actions/setup-rust"
        with:
          target: "${{ matrix.target }}"

      - name: "Run Cargo test"
        run: "cargo test --all --locked --target ${{ matrix.target }}"
